#!/bin/bash

echo "enter marks"
read marks

if [[ $marks -gt 90 ]] ; then
	echo "distinction"
elif [[ $marks  -gt 75 && $marks -lt 90 ]] ; then
	echo "first"
elif [[ $marks -gt 60 && $marks -lt 60 ]] ; then
	echo "second"
elif [[ $marks -gt 35 && $marks -lt 60 ]] ; then
	echo "pass"
else
	echo "invalid"
fi
